### ISSUE TITLE
报错：Agda语言未加载，语法高亮显示回退到使用 txt模式。

### ISSUE THREAD

**Issue by hututusb** [elog-x/yuque-vitepress#9]
```md
D:\UGit\yuque-vitepress>pnpm run docs:dev

> yuque-vitepress@1.0.0 docs:dev D:\UGit\yuque-vitepress
> vitepress dev docs


The language 'agda' is not loaded, falling back to 'txt' for syntax highlighting.

The language 'agda' is not loaded, falling back to 'txt' for syntax highlighting. (x2)
failed to start server. error:
end of the stream or a document separator is expected at line 17, column 1:
    $arr  = mt_rand( 0, count( $file ...
    ^
YAMLException: end of the stream or a document separator is expected at line 17, column 1:
    $arr  = mt_rand( 0, count( $file ...
    ^
    at generateError (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:20090:11)
    at throwError (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:20096:10)
    at readDocument (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:21468:6)
    at loadDocuments (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:21511:6)
    at load (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:21537:20)
    at Object.safeLoad (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:21560:11)
    at parse$2 (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:22889:18)
    at parseMatter (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:23007:18)
    at matter (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:22948:11)
    at md.render (file:///D:/UGit/yuque-vitepress/node_modules/.pnpm/vitepress@1.5.0_@algolia+client-search@5.15.0_@types+node@22.10.1_postcss@8.4.49_search-insights@2.17.3_typescript@4.9.5/node_modules/vitepress/dist/node/chunk-DMuPggCS.js:23136:45)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by hututusb** [comment]
已解决，部分markdown中使用了adga语言，
